worker_processes 1;
pid /home/container/run/nginx.pid;
error_log /home/container/logs/nginx-error.log;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    client_body_temp_path /home/container/run/nginx-client-body;
    proxy_temp_path       /home/container/run/nginx-proxy;
    fastcgi_temp_path     /home/container/run/nginx-fastcgi;
    uwsgi_temp_path       /home/container/run/nginx-uwsgi;
    scgi_temp_path        /home/container/run/nginx-scgi;

    sendfile on;
    keepalive_timeout 65;

    include /etc/nginx/sites-enabled/*.conf;
}
